version: '3'
services:
  db:
    image: mysql:8.0.31
    restart: unless-stopped
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  wordpress:
    image: wordpress:6.1.1-php8.0-fpm-alpine
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - /home/ubuntu/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini  
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - app-network       
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - /home/ubuntu/wordpress/nginx-conf/:/etc/nginx/conf.d
      - /home/ubuntu/wordpress/certs:/etc/certs
    networks:
      - app-network
volumes:
    wordpress:
    dbdata:
networks:
 app-network:
   driver: overlay
